version: '3.8'

services: 
    web:
        build: .
        command: python /code/weekly/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code/weekly
        ports:
            - 8000:8000
